version: '3'

services:
  fast-data-dev:
    image: landoop/fast-data-dev:cp4.0
    container_name: fast-data-dev
    ports:
      - "3030:3030"  # Porta para acessar o Landoop UI
      - "8081:8081"  # Porta para o Schema Registry
      - "9092:9092"  # Porta para o Kafka Broker
      - "8082:8082"  # Porta para o REST Proxy
      - "9581:9581"  # Porta para o Landoop Mock Data Generator
    environment:
      - ADV_HOST=127.0.0.1  # Configura o host para 127.0.0.1 para acesso local
      - RUNTESTS=0  # Desabilita a execução de testes durante a inicialização
      - FORWARDLOGS=0
      - SAMPLEDATA=0
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock  # Monta o socket do Docker para permitir interação com o Docker host
    networks:
      - fast-data-dev-network  # Cria uma rede para comunicação entre os serviços

networks:
  fast-data-dev-network:
    driver: bridge